name: Check and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: cargo fmt --check

      # Check with all features
      - name: Build (all features)
        run: cargo build --all-targets --all-features
      - name: Clippy (all features)
        run: cargo clippy --all-targets --all-features

      # Check without any features
      - name: Build (no features)
        run: cargo build --all-targets
      - name: Clippy (no features)
        run: cargo clippy --all-targets

      # Run tests with all features
      - name: Run tests
        run: cargo test --all-features

      # Run examples
      - name: Run examples
        run: |
          for example in $(ls examples/ | sed 's/\.rs$//'); do
            echo "Running example $example with all features"
            cargo run --example $example --all-features
          done

  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-semver-checks
        run: cargo binstall -y cargo-semver-checks
      - name: Check
        run: cargo semver-checks check-release -p await-tree
